### ISSUE TITLE
Proxy+

### ISSUE THREAD

**Issue by chussenot** [alextanhongpin/terraform-aws#1]
For your Proxy+ issue here
https://github.com/alextanhongpin/terraform-aws/blob/16a9634a356d2f42aecf61886ae5c4b4cd311e31/modules/aws/api-gateway/main.tf#L17

You can take a look at my exemple here
https://github.com/d2si-oss/demo-aws-lambda-buffer-api/blob/master/infra/application/buffer/main.tf#L101

Cheers,

**Comment by alextanhongpin** [comment]
Awesome, will try that out! 

Cheers
